# .github/workflows/test.yml
name: CI

on:
  push:
    branches:
      - "**"   # run on all branches
  pull_request:  # optional, runs on PRs too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
